# Generated by Django 4.1.3 on 2024-05-25 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Concept",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("priority", models.IntegerField(blank=True, default=0)),
                ("comp_score", models.IntegerField(blank=True, default=0)),
                ("description", models.TextField(blank=True, default="")),
                ("vector_representation", models.TextField(blank=True, default="")),
                (
                    "prior_concepts",
                    models.ManyToManyField(
                        blank=True, related_name="prerequisites", to="api.concept"
                    ),
                ),
                (
                    "related_concepts",
                    models.ManyToManyField(
                        blank=True, related_name="related_to", to="api.concept"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SuperConcept",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "concepts",
                    models.ManyToManyField(
                        related_name="super_concepts", to="api.concept"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserChattingRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("chat_history", models.TextField(blank=True, default="")),
                ("name", models.TextField(blank=True, default="new_chat_room")),
                ("vector_representation", models.TextField(blank=True, default="")),
                (
                    "super_concept",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.superconcept",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("summary", models.TextField()),
                ("link", models.URLField()),
                (
                    "concepts",
                    models.ManyToManyField(related_name="articles", to="api.concept"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
