# Generated by Django 4.1.3 on 2024-05-25 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_article_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="concept",
            name="prior_concepts",
            field=models.ManyToManyField(
                blank=True, related_name="prerequisites", to="api.concept"
            ),
        ),
        migrations.AlterField(
            model_name="concept",
            name="related_concepts",
            field=models.ManyToManyField(
                blank=True, related_name="related_to", to="api.concept"
            ),
        ),
    ]
