# Generated by Django 4.1.3 on 2024-05-25 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_concept_prior_concepts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='priority',
            field=models.IntegerField(null=True),
        ),
    ]
