# Generated by Django 4.1.3 on 2024-05-25 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_concept_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='comp_score',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='concept',
            name='priority',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
