# Generated by Django 4.1.3 on 2024-05-25 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_concept_comp_score_alter_concept_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='vector_representation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='concept',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
